df <- read.delim("household_power_consumption.txt", sep = ";")
df$Date <- as.Date(df$Date, format = "%d/%m/%Y")
df$datetime <- paste(df$Date, df$Time)
df$datetime <- strptime(df$datetime, format = "%Y-%m-%d %H:%M:%S")
library("rio")
library("dplyr")
df1 <- subset(df, df$datetime >= strptime("2007-02-01 00:00:00", format = "%Y-%m-%d %H:%M:%S") & df$datetime <= strptime("2007-02-02 24:00:00", format = "%Y-%m-%d %H:%M:%S"))
png(filename="plot2.png", width=480, height=480)
plot(df1$datetime, as.numeric(df1$Global_active_power), xlab = "", ylab="Global Active Power (kilowatts)", type ="l")
dev.off()
